#spring.application.name=SOA-api-gateway
server:
  port: 8080

spring:
  application:
    name: SOA-api-gateway
  cloud:
    gateway:
      routes:
        # Route 1: Orders
        - id: order-route
          uri: lb://ORDER-SERVICE  # 'lb' means Load Balanced (uses Eureka)
          predicates:
            - Path=/api/orders/** # Match anything starting with /api/orders
          filters:
            - StripPrefix=1        # Remove '/api' before forwarding

        # Route 2: Inventory
        - id: inventory-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true # Automatically create routes based on Service IDs in Eureka
#          lower-case-service-id: true # /INVENTORY-SERVICE/ becomes /inventory-service/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/